language: python

python:
	- "2.6"
	- "2.7"
	# - "3.2"
	# - "3.3"
	# - "3.4"

install:
	- pip install -rtests/requirements.txt
	- pip install .

script: python setup.py nosetests

after_success: coveralls
